### ISSUE TITLE
No server file

### ISSUE THREAD

**Issue by RiversideRocks** [repotemplates/NodeJS_StarterTemplate#1]
Hi, it looks like you dont have a nodejs file.

**Comment by code-alt** [comment]
and so you can't use the site

**Comment by LankyBox01** [comment]
could you guys make a pull req adding all the necessary files so i can merge it?

**Comment by RiversideRocks** [comment]
Why don't you do it?

**Comment by LankyBox01** [comment]
I am not really specialized in NodeJS...

**Comment by RiversideRocks** [comment]
You could use a tutorial?

**Comment by aboutDavid** [comment]
You made a Node.js starter template but you don't really know how to use Node.js?

**Comment by code-alt** [comment]
The heck with this, I am outta here.

**Comment by LankyBox01** [comment]
> You made a Node.js starter template but you don't really don't know how to use Node.js?

well, i just want to have as many templates, sorry.
